apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricPeer
metadata:
  creationTimestamp: null
  name: org1-peer1
  namespace: org1
spec:
  affinity: null
  couchDBexporter: null
  couchdb:
    externalCouchDB: null
    image: couchdb
    password: couchdb
    pullPolicy: ""
    tag: 3.1.1
    user: couchdb
  discovery:
    period: 60s
    touchPeriod: 60s
  dockerSocketPath: ""
  env: null
  external_chaincode_builder: false
  externalBuilders:
  - name: ccaas_builder
    path: /opt/hyperledger/ccaas_builder
    propagateEnvironment:
    - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG
  externalEndpoint: peer1-org1.fabric.chikitsa.io:443
  fsServer: null
  gatewayApi:
    gatewayName: hlf-gateway
    gatewayNamespace: default
    port: 443
  gossip:
    bootstrap: ""
    endpoint: ""
    externalEndpoint: peer1-org1.fabric.chikitsa.io:443
    orgLeader: false
    useLeaderElection: true
  grpcProxy: null
  hostAliases: null
  hosts:
  - peer1-org1.fabric.chikitsa.io
  image: hyperledger/fabric-peer
  imagePullPolicy: Always
  imagePullSecrets: null
  istio:
    hosts:
    - peer1-org1.fabric.chikitsa.io
    ingressGateway: ingressgateway
    port: 443
  logging:
    cauthdsl: info
    gossip: info
    grpc: info
    ledger: info
    level: info
    msp: info
    peer: info
    policies: info
  mspID: Org1MSP
  replicas: 1
  resources:
    chaincode:
      limits:
        cpu: "1"
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 10m
    couchdb:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 10m
    couchdbExporter: null
    peer:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
    proxy: null
  secret:
    enrollment:
      component:
        cahost: org1-ca.fabric.chikitsa.io
        caname: ca
        caport: 443
        catls:
          cacert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNZakNDQWdlZ0F3SUJBZ0lSQUlIU2RKU1RuWFRrbWFpVzV2OU1JLzR3Q2dZSUtvWkl6ajBFQXdJd1VqRVQKTUJFR0ExVUVCaE1LUTJGc2FXWnZjbTVwWVRFSk1BY0dBMVVFQnhNQU1Ra3dCd1lEVlFRSkV3QXhGREFTQmdOVgpCQW9UQzBoNWNHVnliR1ZrWjJWeU1ROHdEUVlEVlFRTEV3WkdZV0p5YVdNd0hoY05Nak14TURFNU1EY3hNREk0CldoY05Nek14TURJd01EY3hNREk0V2pCU01STXdFUVlEVlFRR0V3cERZV3hwWm05eWJtbGhNUWt3QndZRFZRUUgKRXdBeENUQUhCZ05WQkFrVEFERVVNQklHQTFVRUNoTUxTSGx3WlhKc1pXUm5aWEl4RHpBTkJnTlZCQXNUQmtaaApZbkpwWXpCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkQxK280aldoSUhQeWVoQ0YwU05WMlFxCkUxb0xCZzI0UkZkYVRhWHJPbGtxQzAvUDlBdzdYbkhRbk5sdzM2TGJ6NUtoRVhDRXlUUm4rR09ZSEpueDU1eWoKZ2Iwd2dib3dEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRgpCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUNrR0ExVWREZ1FpQkNBeGh1WStwY21wTTk0SlRncTNlK3lUCmNBRVdnYTl1TW8yNkszcXo4QS94UERCTkJnTlZIUkVFUmpCRWdnbHNiMk5oYkdodmMzU0NCMjl5WnpFdFkyR0MKREc5eVp6RXRZMkV1YjNKbk1ZSWFiM0puTVMxallTNW1ZV0p5YVdNdVkyaHBhMmwwYzJFdWFXK0hCSDhBQUFFdwpDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBSkdVek83K3JUVU5PanlKRGhTWDNuL3ZDaXp5cnp3YnF6QzRLSEFSCm1mWWdBaUVBOE11azdOK3R2Z3EzZmw5VnJ2OXhRQTk5WHB0b0VwZGU3WXRrS09KN29tTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        enrollid: peer1
        enrollsecret: peer1pw
        external: null
      tls:
        cahost: org1-ca.fabric.chikitsa.io
        caname: tlsca
        caport: 443
        catls:
          cacert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNZakNDQWdlZ0F3SUJBZ0lSQUlIU2RKU1RuWFRrbWFpVzV2OU1JLzR3Q2dZSUtvWkl6ajBFQXdJd1VqRVQKTUJFR0ExVUVCaE1LUTJGc2FXWnZjbTVwWVRFSk1BY0dBMVVFQnhNQU1Ra3dCd1lEVlFRSkV3QXhGREFTQmdOVgpCQW9UQzBoNWNHVnliR1ZrWjJWeU1ROHdEUVlEVlFRTEV3WkdZV0p5YVdNd0hoY05Nak14TURFNU1EY3hNREk0CldoY05Nek14TURJd01EY3hNREk0V2pCU01STXdFUVlEVlFRR0V3cERZV3hwWm05eWJtbGhNUWt3QndZRFZRUUgKRXdBeENUQUhCZ05WQkFrVEFERVVNQklHQTFVRUNoTUxTSGx3WlhKc1pXUm5aWEl4RHpBTkJnTlZCQXNUQmtaaApZbkpwWXpCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkQxK280aldoSUhQeWVoQ0YwU05WMlFxCkUxb0xCZzI0UkZkYVRhWHJPbGtxQzAvUDlBdzdYbkhRbk5sdzM2TGJ6NUtoRVhDRXlUUm4rR09ZSEpueDU1eWoKZ2Iwd2dib3dEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRgpCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUNrR0ExVWREZ1FpQkNBeGh1WStwY21wTTk0SlRncTNlK3lUCmNBRVdnYTl1TW8yNkszcXo4QS94UERCTkJnTlZIUkVFUmpCRWdnbHNiMk5oYkdodmMzU0NCMjl5WnpFdFkyR0MKREc5eVp6RXRZMkV1YjNKbk1ZSWFiM0puTVMxallTNW1ZV0p5YVdNdVkyaHBhMmwwYzJFdWFXK0hCSDhBQUFFdwpDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBSkdVek83K3JUVU5PanlKRGhTWDNuL3ZDaXp5cnp3YnF6QzRLSEFSCm1mWWdBaUVBOE11azdOK3R2Z3EzZmw5VnJ2OXhRQTk5WHB0b0VwZGU3WXRrS09KN29tTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        csr:
          cn: ""
          hosts:
          - 127.0.0.1
          - localhost
          - 18.60.97.75
          - 18.61.23.151
          - 18.61.53.187
          - org1-peer1
          - org1-peer1.org1
          - peer1-org1.fabric.chikitsa.io
        enrollid: peer1
        enrollsecret: peer1pw
        external: null
  service:
    type: ClusterIP
  serviceMonitor: null
  stateDb: couchdb
  storage:
    chaincode:
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: fabric-sc
    couchdb:
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: fabric-sc
    peer:
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: fabric-sc
  tag: 2.5.3
  tolerations: null
  updateCertificateTime: null

