apiVersion: v1
kind: Service
metadata:

  labels:
    app: ipfs-cluster-gateway
  name: ipfs-cluster-gateway
  namespace: ipfs

spec:
 
  ports:
  - name: http

    port: 8080
    protocol: TCP
    targetPort: http

  selector:
    app: ipfs-cluster
  
  type: ClusterIP

